-- Drop existing type if exists
DROP TYPE IF EXISTS work_center_enum CASCADE;

-- Create new work_center_enum type with updated values
CREATE TYPE work_center_enum AS ENUM (
  'MADRID HOGARES DE EMANCIPACION V. DEL PARDILLO',
  'ALAVA HAZIBIDE',
  'SANTANDER OFICINA',
  'MADRID CUEVAS DE ALMANZORA',
  'SEVILLA ROSALEDA',
  'SEVILLA CASTILLEJA',
  'SANTANDER ALISAL',
  'VALLADOLID MIRLO',
  'MURCIA EL VERDOLAY',
  'BURGOS CERVANTES',
  'MADRID OFICINA',
  'LA LINEA CAI / CARMEN HERRERO',
  'CADIZ CARLOS HAYA',
  'MADRID ALCOBENDAS',
  'MADRID MIGUEL HERNANDEZ',
  'MADRID HUMANITARIAS',
  'MADRID VALDEBERNARDO',
  'MADRID JOSE DE PASAMONTE',
  'MADRID IBIZA',
  'MADRID PASEO EXTREMADURA',
  'MADRID DIRECTORES DE CENTRO',
  'MADRID GABRIEL USERA',
  'MADRID ARROYO DE LAS PILILLAS',
  'MADRID CENTRO DE DIA CARMEN HERRERO',
  'MADRID HOGARES DE EMANCIPACION SANTA CLARA',
  'MADRID HOGARES DE EMANCIPACION BOCANGEL',
  'MADRID AVDA DE AMERICA',
  'MADRID VIRGEN DEL PUIG',
  'MADRID ALMACEN',
  'MADRID HOGARES DE EMANCIPACION ROQUETAS',
  'ALAVA PAULA MONTAL',
  'ALAVA SENDOA',
  'ALAVA EKILORE',
  'ALAVA GESTIÓN AUKERA',
  'ALAVA GESTIÓN HOGARES',
  'ALAVA XABIER',
  'ALAVA ATENCION DIRECTA',
  'ALAVA PROGRAMA DE SEGUIMIENTO',
  'SANTANDER MARIA NEGRETE (CENTRO DE DÍA)',
  'SANTANDER ASTILLERO',
  'BURGOS CORTES',
  'BURGOS ARANDA',
  'BURGOS OFICINA',
  'LA LINEA ESPIGON',
  'LA LINEA MATILDE GALVEZ',
  'LA LINEA GIBRALTAR',
  'LA LINEA EL ROSARIO',
  'LA LINEA PUNTO DE ENCUENTRO',
  'LA LINEA SOROLLA',
  'CADIZ TRILLE',
  'CADIZ GRANJA',
  'CADIZ OFICINA',
  'CADIZ ESQUIVEL',
  'SEVILLA PARAISO',
  'SEVILLA VARIOS',
  'SEVILLA OFICINA',
  'SEVILLA JAP NF+18',
  'MURCIA HOGAR DE SAN ISIDRO',
  'MURCIA HOGAR DE SAN BASILIO',
  'MURCIA OFICINA',
  'ALICANTE EL PINO',
  'ALICANTE EMANCIPACION LOS NARANJOS',
  'ALICANTE EMANCIPACION BENACANTIL',
  'ALICANTE EL POSTIGUET',
  'PALENCIA',
  'CORDOBA CASA HOGAR POLIFEMO',
  'PROFESIONALES'
);

-- Add work_centers column if it doesn't exist
DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 
        FROM information_schema.columns 
        WHERE table_name = 'employee_profiles' 
        AND column_name = 'work_centers'
    ) THEN
        ALTER TABLE employee_profiles
        ADD COLUMN work_centers work_center_enum[] DEFAULT '{}';
    END IF;
END $$;

-- Create index for work_centers
CREATE INDEX IF NOT EXISTS idx_employee_profiles_work_centers 
ON employee_profiles USING gin(work_centers);